%Setup Drone
m = 0.2
I= [[0.1,0,0]; [0, 0.1, 0]; [0,0,0.08]]
% sample time
ts= 0.01
% Initial States (Initial XYZ is generated by XYZsignal script)
Euler_0= [0; 0;0]
XYZ 0 [1;1;0]
body_rate_0= [0;0;0]
% Environment
9 = [0;0; -9.8]